### ISSUE TITLE
Project not working

### ISSUE THREAD

**Issue by NoahClemmensen** [twobitcoder101/Flat#3]
### When building there is build errors.
In FlatUtils.cs and Shapes.cs there is a CS0246 error for missing PolygonShape and CircleShape

Example:
Here the parameter polygon with type PolygonShape is missing, it is not being referenced anywhere.
```
public static void CreateBoundingBox(PolygonShape polygon, out FlatBox box)
        {
            Vector2[] vertices = polygon.Vertices;
            int[] hull = polygon.ConvexHull;

            float xmin = float.MaxValue;
            float xmax = float.MinValue;
            float ymin = float.MaxValue;
            float ymax = float.MinValue;

            for (int i = 0; i < hull.Length; i++)
            {
                Vector2 v = vertices[hull[i]];

                if (v.X < xmin) { xmin = v.X; }
                if (v.X > xmax) { xmax = v.X; }
                if (v.Y < ymin) { ymin = v.Y; }
                if (v.Y > ymax) { ymax = v.Y; }
            }

            box = new FlatBox(new Vector2(xmin, ymin), new Vector2(xmax, ymax));
        }
```

The errors are at
FlatUtil.cs
Line 421, 480, 503 and 547

Shapes.cs
1036

FlatCircle.cs
error CS0103 at 401 and 450

Let me know how to fix it or if I am missing anything. It might be a easy fix and I'm just blind haha

**Comment by twobitcoder101** [comment]
It looks like I forgot to upload the Flat.Physics and Flat.Physics.Shapes files with the rest of the project. Let me see If I can update that… 😊  From: Noah ClemmensenSent: Friday, May 27, 2022 2:32 PMTo: twobitcoder101/FlatCc: SubscribedSubject: [twobitcoder101/Flat] Project not working (Issue #3) When building there is build errors.In FlatUtils.cs and Shapes.cs there is a CS0246 error for missing PolygonShape and CircleShapeExample:Here the parameter polygon with type PolygonShape is missing, it is not being referenced anywhere.public static void CreateBoundingBox(PolygonShape polygon, out FlatBox box)        {            Vector2[] vertices = polygon.Vertices;            int[] hull = polygon.ConvexHull;             float xmin = float.MaxValue;            float xmax = float.MinValue;            float ymin = float.MaxValue;            float ymax = float.MinValue;             for (int i = 0; i < hull.Length; i++)            {                Vector2 v = vertices[hull[i]];                 if (v.X < xmin) { xmin = v.X; }                if (v.X > xmax) { xmax = v.X; }                if (v.Y < ymin) { ymin = v.Y; }                if (v.Y > ymax) { ymax = v.Y; }            }             box = new FlatBox(new Vector2(xmin, ymin), new Vector2(xmax, ymax));        }Let me know how to fix it or if I am missing anything. It might be a easy fix and I'm just blind haha—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by NoahClemmensen** [comment]
Were you able to update it and add it?

**Comment by pwninstein** [comment]
I am also having trouble using the project as-is. Specifically `using Flat.Physics;`, `Collision.IntersectLines`, and `Collision.IntersectLinesFast` are throwing compile-time errors.
